version: '3.8'

services:

  face_id:
    image: face_id
    build: ./face_id_api
    ports: #to the host
        - 8004:8000     #host:container
    ulimits:
      memlock: -1 # set upper limit for how much memory is locked for the container (-1 means lock as much as the container uses)
    shm_size: 4gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./data:/data
    command: uvicorn main:api --host 0.0.0.0
    # restart: always

